nativescript-community/ui-material-components

package.json, packages/nativescript-material-activityindicator/package.json, packages/nativescript-material-bottomsheet/package.json, packages/nativescript-material-button/package.json, packages/nativescript-material-cardview/package.json, packages/nativescript-material-core/package.json, packages/nativescript-material-dialogs/package.json, packages/nativescript-material-floatingactionbutton/package.json, packages/nativescript-material-progress/package.json, packages/nativescript-material-ripple/package.json, packages/nativescript-material-slider/package.json, packages/nativescript-material-snackbar/package.json, packages/nativescript-material-textfield/package.json
Added an npm command `tsc-win` for contributors using Windows machines to use.
=> Added tsc command for Windows machines

README.md, demo/app/examples/snackbar-fragment.ts, demo/app/examples/snackbar-fragment.xml, demo/app/home/home-view-model.ts, packages/nativescript-material-snackbar/README.md, packages/nativescript-material-snackbar/platforms/ios/Podfile, src/snackbar/snackbar.d.ts, src/snackbar/snackbar.ios.ts
Use MaterialComponents/Snackbar pod to implement snackbar for iOS.
=> Implement snackbar for iOS

src/bottomsheet/angular/bottomsheet.service.ts
Fix for when the observable never emits due to a dismiss or closing without params
=> fix: always return correct bottom sheet result

src/bottomsheet/bottomsheet.android.ts
* the last pr fix broke disabling dismissOnDraggingDownSheet
=> fix: bottomsheet android is now handling dismissOnDraggingDownSheet correcly

packages/nativescript-material-bottomnavigationbar/README.md
=> Typo "Android"

README.md
=> Typo "resources"

demo-vue/app/examples/BottomNavigationBar.vue
Tab Pressed, Tab Selected, and Tab Reselected event handlers were missing.
@tabPressed="onBottomNavigationTabPressed"
@tabSelected="onBottomNavigationTabSelected"
@tabReselected="onBottomNavigationTabReselected"
=> Add missing event handlers

demo-ng/src/app/examples/bottom-navigation-bar/third-tab/third-tab.component.html, demo-vue/app/examples/BottomNavigationBar.vue
- Removed commented Angular code in the Vue.js sample and replaced it with a basic Vue.js use case
- Fixed a minor typo in Angular BottomNavigation sample
=> Improve Vue sample and fix typo in Angular sample

src/bottomnavigationbar/bottomnavigationbar.android.ts, src/ripple/ripple.android.ts
closes https://github.com/Akylas/nativescript-material-components/issues/164
=> fix(android): bottomnav and ripple - NativeClass decorations needed

src/bottomsheet/angular/bottomsheet.module.ts
=> typing 'NativeScriptMaterialBottomSheetModule' forRoot fixes #177

src/snackbar/snackbar.android.ts
* the value for SNACKBAR_TEXT_ID was not initialized, bacause the static attribute was used instead of the getter function
=> fix(android) [snackbar] initialization of SNACKBAR_TEXT_ID

demo-ng/nativescript.config.ts, demo-ng/nsconfig.json, demo-ng/package.json, demo-ng/references.d.ts, demo-ng/src/app.css, demo-ng/src/app/app-routing.module.ts, demo-ng/src/app/app.module.ts, demo-ng/src/app/examples/activity-indicator/activity-indicator.module.ts, demo-ng/src/app/examples/bottom-navigation-bar/bottom-navigation-bar.component.ts, demo-ng/src/app/examples/bottom-navigation-bar/bottom-navigation-bar.module.ts, demo-ng/src/app/examples/bottom-sheet/bottom-sheet.module.ts, demo-ng/src/app/examples/buttons/buttons.module.ts, demo-ng/src/app/examples/cards/cards.module.ts, demo-ng/src/app/examples/examples.routing.ts, demo-ng/src/app/examples/progress/progress.module.ts, demo-ng/src/app/examples/ripple/ripple.module.ts, demo-ng/src/app/examples/slider/slider.module.ts, demo-ng/src/app/examples/text-field/text-field.module.ts, demo-ng/src/app/home/home.module.ts, demo-ng/src/main.ts, demo-ng/tsconfig.json, demo-ng/webpack.config.js
The pull request upgrades demo-ng project to Angular 10.x and latest version of NativeScript. demo-ng project should be in working state after this pull request.
=> Fix(demo-ng)  make demo-ng work with angular 10

src/bottomnavigationbar/bottomnavigationbar.ios.ts
This fixes https://github.com/nativescript-community/ui-material-components/issues/208 but I'm not a big fan of the solution.
This is the same solution as you found on ui-drawer that one time. https://github.com/nativescript-community/ui-drawer/commit/d422055c5a82aa85a336c8313bb42020dc1a6424
=> fix: default tab select on iOS v8

src/bottomsheet/angular/bottomsheet.service.ts
Bug Fix for Nativescript version 68 and for this issue #201
=> BugFix Right hand side of instanceof is not an object in NativeScript 6.8

src/ripple/ripple.android.ts
=> fix: tap event prevent by ripple

src/bottomsheet/angular/bottomsheet.service.ts
Fixes #250.
The Angular services erased previous modal instances through its global properties `this.componentView` and `this.detachedLoader`, resetting those properties to a new value each time a new modal was shown. However, we need those properties to be able to close a modal in the `closeCallback` that is exposed to the user.
This meant that if we opened a modal B after we opened a modal A, it was no longer possible to close modal A programmatically, as demonstrated in issue #250.
I tried not changing the code too much, just the necessary bits, however I also reformatted it (according to eslint settings of this repository) and consolidated the types a little.
External API is **not** changed.
Tested on my app with various modals.
=> fix(bottomsheet): support multiple modal instances in the Angular service

packages/bottom-navigation/README.md
=> fix(bottom-navigation): Fix usage doc for Plain NS

packages/bottomsheet/README.md
I'm not convinced to write it like that, but I also think it's better than having nothing. What does @farfromrefug think?
=> (Bottom Sheet) doc add BottomSheetOptions

package.json, packages/core-tabs/package.json, packages/core/package.json
This allows the project to be built on windows. It might address #346
=> fix(build): restore windows build support

package.json
I am trying to build locally but when I run `build.all` I get this error.
```
error Workspaces can only be enabled in private projects
```
=> fix build private repository

src/bottom-navigation/index.ios.ts
=> fix(bottom-navigation): consistent styling on iOS 18
