- src/floatingactionbutton/floatingactionbutton-common.ts
I'm unsure what the `sync` variable was doing, but I've followed the current pattern of commenting it out in the `FloatingActionButton` so as to get local images working for the icon.
> Fixed missing 'sync' error

- packages/nativescript-material-activityindicator/package.json
- packages/nativescript-material-bottomsheet/package.json
- packages/nativescript-material-button/package.json
- packages/nativescript-material-cardview/package.json
- packages/nativescript-material-floatingactionbutton/package.json
- packages/nativescript-material-progress/package.json
- packages/nativescript-material-ripple/package.json
- packages/nativescript-material-slider/package.json
- packages/nativescript-material-snackbar/package.json
- packages/nativescript-material-textfield/package.json
- src/bottomsheet/angular/bottomsheet.module.ts
- src/bottomsheet/angular/bottomsheet.service.ts
- tsconfig.json
Currently most modules are not built with AOT. This ensures all packages that have angular components are built as libraries (`skipTemplateCodegen`) with the angular compiler (`ngc`)
This solves my issues with textfield and bottomsheet (the only two I'm currently using)
> Fix angular AOT compilation

- demo-ng/.gitignore
- demo-ng/package.json
- demo-ng/src/package.json
- demo-ng/tsconfig.json
- demo-ng/tsconfig.tns.json
- demo-ng/webpack.config.js
- Updated demo-ng to 6.1
- renamed app.scss to `css` and imported core-theme to apply the theme-core default styles (currently it was not applied so the app had no styling for the theme-core css being used on elements in the demo)
> update ng-demo to NS 6.1

- src/bottomsheet/bottomsheet.ios.ts
This module `import * as application from 'tns-core-modules/application'` seems never used in bottomsheet.ios.ts, should we remove it?
I removed it and run a test on the iPhone 6 and iPhone X,  without any side effects.
Thanks
> Remove unused module from bottomsheet.ios.ts

- src/textview/textview.ios.ts
The editable prop for textview wasn't being honored. I.e. if it was set to false the textview was still editable
> fix(textview): Editable prop now works

- src/bottomnavigationbar/bottomnavigationbar.android.ts
The code was trying to call `showBadge` on this: https://developer.android.com/reference/com/google/android/material/bottomnavigation/BottomNavigationView
Overwriting this from outside the library with `getOrCreateBadge` works as expected.
> Angular BottomNavigationBar showBadge fix

- package.json
- src/bottomsheet/angular/bottomsheet.service.ts
My fix in [here](https://github.com/Akylas/nativescript-material-components/issues/141) worked for using the nativescript-material-components in Ivy, however there was still an issue with the nativescript-material-bottomsheet when Ivy was turned on. It turns out that it was because the index being passed into the Angular viewContainerRef.createComponent should be 0 based (https://angular.io/api/core/ViewContainerRef#insert) and -1 was being passed in here.
I tested this on both iOS and Android with Ivy turned off and on. Everything is working properly.
> fix(bottomsheet): support Angular Ivy compiler

- src/snackbar/snackbar.android.ts
* the value for SNACKBAR_TEXT_ID was not initialized, bacause the static attribute was used instead of the getter function
> fix(android) [snackbar] NS 6.x - initialization of SNACKBAR_TEXT_ID

- demo-ng/App_Resources/iOS/Podfile
- demo-ng/package.json
- demo-ng/src/app/examples/examples.module.ts
- demo-ng/src/app/examples/examples.routing.ts
- demo-ng/src/app/examples/tabs/tabs.component.html
- demo-ng/src/app/examples/tabs/tabs.component.ts
- demo-ng/src/app/examples/tabs/tabs.module.ts
- demo-ng/src/app/home/home.component.html
- demo-ng/src/app/home/home.component.ts
- src/activityindicator/angular/tsconfig.json
- src/appbar/angular/tsconfig.json
- src/bottomnavigationbar/angular/tsconfig.json
- src/bottomsheet/angular/tsconfig.json
- src/button/angular/tsconfig.json
- src/cardview/angular/tsconfig.json
- src/floatingactionbutton/angular/tsconfig.json
- src/progress/angular/tsconfig.json
- src/ripple/angular/tsconfig.json
- src/slider/angular/tsconfig.json
- src/tabs/angular/package.json
- src/tabs/angular/tsconfig.json
- src/textfield/angular/tsconfig.json
- src/textview/angular/tsconfig.json
The purpose of this PR is as follows:
- ng-packagr dest setting for tabs/angular was not correct, now it's been set correctly.
- tnsconfig.json files in src/*/angular now have angularCompilerOptions.enableIvy set to false to fix ng-packagr warning about Ivy.
- A Tabs example has been added to ng-demo.
- The visual of Examples page has been slightly improved.
- Add Podfile with min version 10.0 to ng-demo App_Resources/iOS
> Improve Angular packaging and Demo

- src/core/textbase/cssproperties.ts
- src/textfield/textfield.android.ts
- src/textfield/textfield.common.ts
- src/textfield/textfield.d.ts
- src/textfield/textfield.ios.ts
- src/textview/textview.android.ts
- src/textview/textview.common.ts
- src/textview/textview.d.ts
- src/textview/textview.ios.ts
This introduces a way to change the color of the helper text on the TextField or TextView components.
```html
<MDTextField
...
helper="help me!"
helperColor="red"
...
></MDTextField>
```
or 
```css
MDTextField {
helper-color: red;
}
```
> helperColor property on TextField and TextView

- src/button/button.android.ts
- src/button/button.ios.ts
I'm getting the following error when building my project:
```
WARNING in ../node_modules/@nativescript-community/ui-material-button/button.js 95:5-26                                           "export 'textTransformProperty' was not found in '@nativescript/core'                                                             
@ ../node_modules/@nativescript-community/ui-material-button/angular/fesm2015/nativescript-community-ui-material-button-angular.js
```
The import was in the correct location here https://github.com/nativescript-community/ui-material-components/blob/dc15bdf0e1cce15a1b9b0f9346530f11b17581d1/src/core/tab-navigation-base/tab-strip/index.ts#L4
Edit: This warning during the build shows up as a runtime error with:
```
JS: TypeError: Cannot read property 'setNative' of undefined …
```
> Moving import to correct location

- packages/bottom-navigation/README.md
The tags in the documentation for Bottom Navigation are not correct. On multiple places the `MD` prefix is missing. This MR fixes tgat
> Fix bottom navigation tags

- packages/tabs/README.md
The tag ending was incorrect in the doc. This PR fixes that.
> Fix ending MDTabStripItem tag

- src/tabs/tabs.ios.ts
Setting the un-selected-item-color caused apps to crash with the below output. This fixes it 😄 
```
file: mobile/src/tabs.ios.ts:1001:85: JS ERROR TypeError: undefined is not an object (evaluating 'this._selectedItemColor.ios')
NativeScript caught signal 11.
Native Stack:
1   0x1084f2171 sig_handler(int)
2   0x10e7225fd _sigtramp
3   0x12abf0000
4   0x10e660b4d libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x10e664e4c _Unwind_RaiseException
6   0x10e2404aa __cxa_throw
7   0x10ca49bfa _objc_exception_destructor(void*)
8   0x1084a1b6f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
9   0x1084e23a8 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, …
```
> fix(tabs ios): Setting unselected color crashes app

- src/core/tab-navigation-base/tab-navigation-base/index.ts
- src/core/tab-navigation-base/tab-strip/index.ts
- src/tabs/tabs.ios.ts
The highlight-color and ripple-color css props for MDTabStrip were not working on iOS, they do now.
```
MDTabStrip {
highlight-color: #ffff00; //yellow
ripple-color: #ff0000; //red
}
```
Before with the above css:
After with the above css:
> fix(tabs ios): selector and ripple color css

- src/bottomnavigationbar/bottomnavigationbar-common.ts
- src/bottomnavigationbar/bottomnavigationbar.d.ts
Currently the badge is removed when the tab is pressed or selected.
I suggest we leave it up to the user to determine when to clear the badge. There's the case where the badge is showing a notification count that may change when reading/clearing notifications. Without this, we have to repeatedly show the badge during navigation.
> feat(bottomnavigationbar) persist badge on pressed/selected

- src/bottomsheet/bottomsheet-common.ts
- src/bottomsheet/bottomsheet.android.ts
Disables the collapsed/peeked state of the bottomsheet when the initial view height is greater than 50% of the viewport. 
Unaware of how the iOS version functions let alone if something like this is needed in it.
> [BottomSheet]Android skipCollapsedState

- demo-ng/package.json
- demo-ng/src/app/examples/bottom-navigation-bar/bottom-navigation-bar.component.html
- package.json
- packages/activityindicator/package.json
- packages/bottom-navigation/package.json
- packages/bottomnavigationbar/package.json
- packages/bottomsheet/package.json
- packages/button/package.json
- packages/cardview/package.json
- packages/core/package.json
- packages/dialogs/package.json
- packages/floatingactionbutton/package.json
- packages/progress/package.json
- packages/ripple/package.json
- packages/slider/package.json
- packages/snackbar/package.json
- packages/speeddial/package.json
- packages/tabs/package.json
- packages/textfield/package.json
- packages/textview/package.json
Also bump nativescript/core in angular-demo  to fix issue with accessibility error being logged.
Also added build.all.win option, to ease building on windows.
> chore: Update angular demo for bottomsheet to show font icon example.

- src/bottomsheet/bottomsheet-common.ts
- src/bottomsheet/bottomsheet.android.ts
Added functionality to not discard the sheet when pressing on the android back button
> feat(BottomSheet): add suport dismissOnBackButton

- src/bottomsheet/bottomsheet-common.ts
- src/bottomsheet/bottomsheet.android.ts
- src/bottomsheet/bottomsheet.ios.ts
Related to https://github.com/nativescript-community/ui-material-components/issues/306
> feat(BottomSheet): add default collapsed sheet height for android

- src/bottomsheet/bottomsheet-common.ts
- src/bottomsheet/bottomsheet.ios.ts
For a sheet to expand, you need to set the trackingScrollView according to the [documentation](https://github.com/material-components/material-components-ios/tree/develop/components/BottomSheet#expanding-bottom-sheet-example). Then I realized that it did not work. Now it is spreading and collapsing!
> fix: (iOS) fix trackingScrollView and peekHeight

- src/bottomsheet/bottomsheet-common.ts
- src/bottomsheet/bottomsheet.android.ts
- src/bottomsheet/bottomsheet.ios.ts
Add functionality like provided in android, but it works for ios and android.
Logic reference: https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetBehavior.BottomSheetCallback
> feat: BottomSheet add callback onChangeState

- src/bottom-navigation/index.ios.ts
* This will solve the issue discussed in Discord recently: https://discord.com/channels/603595811204366337/751068755206864916/892445879129210920
* Tabstrip items would end up with completely transparent background colors and exhibit strange color behavior when switching tabs
* I contemplated using a majorVersion >= 15 to only apply for iOS 15 in the fallback however it doesn't matter. The default behavior was always to be white when no background-color was set so this just ensures standard behavior stays same as always but also ensure building with Xcode 13 or greater retains default behavior
* You can also add a class to each `MDTabStripItem` with a `background-color` set however I would not rely on developers doing this or leaving them to figure that out in this case
> fix(bottom-navigation): Xcode 13 background-color correction

- src/bottom-navigation/index.ios.ts
On production I'm getting sporadic crashes on the `this._owner.get()` line of the bottom navigation. I'm guessing it happens in some suspend/kill situations as it does not occur very often. The PR adds a safety check if there is an owner before trying to call any methods on it.
> feat(bottom-navigation): Add safety check for owner

- src/tabs/tabs.android.ts
@farfromrefug we were unsure this fix was needed, but apparently it is, as tabs break on modal pages
> fix(tabs): use relative fragment manager

- src/bottomsheet/bottomsheet.ios.ts
* the right and bottom values erroneously subtract the left and top distances, respectively
* the error only appears when there are safe areas on the sides, for example on an iPhone X
* removing the subtraction is correcting this issue
> fix (bottomsheet ios) corrected width on safe areas

- packages/core-tabs/platforms/android/java/com/nativescript/material/core/TabStrip.java
- packages/core-tabs/platforms/android/java/com/nativescript/material/core/TabsBar.java
Behavior:
https://user-images.githubusercontent.com/4061767/167474305-78c9c0ad-9b86-4dbc-a659-10250692f529.mov
Also improves on `setDistributeEvenly` to ensure the sizing is correct at all times.
> fix(tabs): correctly calculate sizing and animation positions

- src/slider/slider.ios.ts
Here's a small fix on iOS so that `numberOfDiscreteValues` has the correct value.
With the previous logic the slider resulted in always being continuous as it calculated the min/max difference rather than the amount of values in the range.
**Examples**
**Range** 0 - 10
**Steps** 1
**Calculation** 10 - 0 / 1 = 10
**New Calculation** (10 - 0 + 1) / 1 = 11
<hr>
**Range** 5 - 100
**Steps** 5
**Calculation** 100 - 5 / 5 = 19
**New Calculation** (100 - 5 + 1) / 5 = 20 (Actual value is 19.2 but code is using `Math.ceil()` to get a whole number)
<hr>
Tested this locally on my project, unfortunately I wasn't able to run the demo apps within this project itself. But I think it should be fine.
Let me know if any other updates are required.
> iOS Slider numberOfDiscreteValues fix

- src/bottomsheet/bottomsheet-common.ts
- src/bottomsheet/bottomsheet.android.ts
When you have a sheet open in the middle of the screen you cannot interact with the screen behind it, this PR adds that you can interact.
For now it only supports Android, I want to make it work for iOS too
old behavior:
https://user-images.githubusercontent.com/15719383/184112618-12c07bbb-1b10-418d-809c-f19a5f81a4bd.mp4
new behavior:
https://user-images.githubusercontent.com/15719383/184112497-45eca734-d8c3-4fa8-849f-a3bd73fce1cc.mp4
> feat(BottomSheet): (Android only) allows to interact with the screen behind the sheet

- src/core-tabs/tab-content-item/index.android.ts
This fixes issues in nested tabs where it can't find the fragment. Although it doesn't crash, the fragments enter a weird state where there are some leaks during navigations, which might or might not be related to this plugin.
The problem here is that the tab fragments are always added to the root manager (due to passing _context) on the fragment adapter. Ideally we should pass the child fragment manager but this seems to works on all the scenarios I tested (nested frames, single frame, tabs in modal, nested frames in modal).
My initial tests passing the correct manager resulted in a weird crash in the adapter constructor which might be related to picking the wrong constructor or just some weirdness on my test app, since this fix seemed to resolve all issues I decided to leave it as is, …
> fix: correctly search for the tab fragment

- src/bottomnavigationbar/bottomnavigationbar.android.ts
Sometimes it was throwing "`.getMenu()` of undefined" error.
> fix(bottomnavigationbar): select tab native view

- packages/bottomsheet/README.md
- src/bottomsheet/bottomsheet.android.ts
When we have a map behind the sheet the movement becomes slow, when we add this flag the map becomes fluid to touch and movement without any problem
Before:
https://user-images.githubusercontent.com/15719383/195977059-b3e5875c-6760-40cc-9ea3-41fc519baee7.mp4
After:
https://user-images.githubusercontent.com/15719383/195977071-559b02f4-15dd-43fe-8748-d5e9020db287.mp4
Note how the movement of the map when the sheet is opened or when it is open has lag and with the flag this problem disappears
> fix(BottomSheet): Back to blade motion is fluid

- src/textfield/textfield.android.ts
- src/textfield/textfield.ios.old.ts
- src/textfield/textfield.ios.ts
@farfromrefug I've checked all the `ui-material-components` I think that only the textfield that is require update .. I am not sure because I've updated the plugin that I use and I see errors!
I think the main change are the `layout` import from mainly UI plugins, and there some think bizarre with the WeakRef that become an `interface` instead !!
> Update to NS 8.4

- packages/core-tabs/platforms/android/java/com/nativescript/material/core/TabsBar.java
When we have more tabs and swipe to the left tab pages, but the corresponding active tab is not showing, we need to scroll the tabor to the left to see the active tab.
Please see the issue being reproduced:
https://user-images.githubusercontent.com/5738416/206513840-c6c0ce95-094b-402e-aa1e-443b88dfe4f0.mov
Please see the behavior after the bugfix applied:
https://user-images.githubusercontent.com/5738416/206513952-449bd80f-012c-4be8-bc4b-fb10373651a1.mp4
> fix(tabs): active tabitem isn't visible

- src/tabs/index.ios.ts
Setting `tabStrip.visibility` to hidden/collapse/visible now works correctly.
Also, `tabs.tabStrip = null` and then `tabs.tabStrip = newTabstrip` also works now
> fix(tabs): handle removing, re-adding, and changing visibility of tabstrip

- src/core-tabs/tab-navigation/index.android.ts
TabStrip style for the unselected item is not working.
Example CSS file:
```css
MDTabStrip {
background-color: #79d2a6;
selected-item-color: red;
un-selected-item-color: yellow;
highlight-color: red;
}
TabStripClassStyle MDTabStripItem {
background-color: #79d2a6;
}
```
Before bugfix:
https://user-images.githubusercontent.com/5738416/219018760-5b8756a3-85e1-4f3b-80cb-fb21084a0c8f.mp4
After bugfix:
https://user-images.githubusercontent.com/5738416/219018836-c5ee6a6a-a258-4b95-98b0-dc6f3acde74c.mp4
Resolution: 
The mUnSelectedItemColor filled up on the CSS file should have greater priority than the default color.
> fix(android): TabStrip style for the unselected item is not working

- demo-snippets/vue/BottomSheet.vue
- demo-snippets/vue/BottomSheetInner.vue
- demo-snippets/vue3/BottomSheet.vue
- demo-snippets/vue3/BottomSheetInner.vue
- demo-snippets/vue3/BottomSheetInnerKeyboard.vue
- demo-snippets/vue3/install.ts
- package.json
- packages/bottomsheet/README.md
- src/bottomsheet/vue/index.ts
- src/bottomsheet/vue3/index.ts
Currently the only way to get an update from  the bottomsheet vue component is via directly calling the $closeBottomSheet method with some return arguments.  
However, when a user swipes to close the bottomsheet there is no opportunity for us to call $closeBottomSheet.  
This pull request adds the ability to directly apply listeners to the vue component in the bottomsheet so that we can get updates from it.
> feat: add vue2 & vue3 listener support to bottomsheet

- packages/core-tabs/platforms/android/java/com/nativescript/material/core/TabsBar.java
- src/tabs/index.android.ts
- src/typings/extensions.android.d.ts
Android Issue:  Active Tab item not displaying after nav back
Reproduce steps:
1. On app with multiple (overflown) tab items, Switch to the last tab item
2. Navigate to a new page
3. Nav back to the page with Tabs
4. Notice the active last tab item is not showing. The tab strip is showing the most left / initial tab items instead.
Expect: the tab strip to show the last displayed position before navigating to the new page.
Video:
https://user-images.githubusercontent.com/5738416/224697030-f659224c-cfc5-4531-8dd6-f10b84a0c1de.mov
> fix(android): active tab not displaying after nav back to page

- src/tabs/index.ios.ts
Use `objectAtIndex` to index into NSArray, fixing issue with IOS for NS 8.5
> fix(tabs): NSArray Indexing

- src/bottom-navigation/index.ios.ts
In IOS the icon color doesn't change correctly is seems that is due to a miss in the code.
`isFontIcon` is not set correctly if the image type is a font icon .. and it was set as constant also!
> [bottom-navigation] Fixe IOS icon color

- src/bottomsheet/bottomsheet.ios.ts
- yarn.lock
@farfromrefug  When this line was executed this._onDismissBottomSheetCallback() it caused this to be executed: https://github.com/nativescript-community/ui-material-components/blob/master/src/bottomsheet/bottomsheet.ios.ts#L449 As it had been set to null, the function failed when trying to access `.nsAnimated` from a null
> fix(bottomSheet): ios viewController undefined on tap in background

- src/core-tabs/tab-content-item/index.android.ts
- src/core-tabs/tab-navigation/index.android.ts
- src/core/android/utils.ts
- yarn.lock
fixes the issue introduced in https://github.com/nativescript-community/ui-material-components/commit/72e442da0c84f42826af14f4fbfb497ab619a7d9#r151328451 when using a non-latest core version
> fix: support both old and new gridlayout addRow APIs

- packages/core-tabs/platforms/android/java/com/nativescript/material/core/TabsBar.java
Tab bar was jump scrolling when scroll settled. Instead, now we just make sure that it's visible.
Also, when animations are disabled and we force the transiton, we make sure that the tab is visible as well
> fix: lazy tab bar slow with or without animations
